### ISSUE TITLE
Skylanders imaginators support

### ISSUE THREAD

**Issue by Naznarok** [jgernandt/blender-hkx#3]
Hello! Coud you add "skylanders imaginators" skeletal animations support for blender? I have sample files in [this](https://www.dropbox.com/s/5ee9jm74bi6d9mp/skylanders_imaginators.zip?dl=0) atchive (model (glb/fbx), hkx animation file and textures).

**Comment by jgernandt** [comment]
Sorry for the late response. I'm not likely to add features at the moment.
