### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by StevedaveTodd** [jgernandt/blender-hkx#5]
Hello, I am a fairly inexperienced modder. I work mainly with the Skyrim SSE CreationKit.  I would love to delve deeper into animations with hkx. I have made some good custom doors and containers etc. that are animated with Blender and Nifskope, and some really good static meshes and LOD meshes. I have been searching for quite a while on how to get hkx files made with Blender and finally stumbled on the blender-hkx tool. I cannot for the life of me figure out how to build the tool from source. I have the visual studio 2019, the havok 2010 skd, the pugixml and your blender addon folder downloaded and have fired up the blender-hkx.sin. 
I keep running into errors with cannot open the source file, or cannot open include file 'Common/Base/hkBase.h' : No such file or directory. 
Online searches lead me adding directories to the addition include directories, but no good results. I have no clue about Visual Studio, is there a specific location I need to download to, keep, or install any of these folders at. Do I lump all of the needed files into one folder. Sorry to bug you with a mundaine question, and I am not looking for you to do a step by step tutorial, I just have no clue where to start with this. I haven't had too many issues with Blender or Nifskope etc. that I haven't been able to solve, but this is beyond me. 
Thank you so very much for any time you are willing to put into this!!!

**Comment by jgernandt** [comment]
Possibly, you'll have the least headache if you mimic my exact folder structure. Starting from some root folder which can be named anything:
* root\blender-hkx (my git)
* root\pugixml (their git)
* root\Havok SDK\hk2010_2_0_r1 (everything from the Havok SDK, which should have the folders Lib and Source)

Otherwise, you can change the paths to these locations in Project>Properties>C/C++>General>Additional Include Directories and Project>Properties>Linker>General>Additional Library Directories.

**Comment by StevedaveTodd** [comment]
Thank you very much for that info. I did get it to build. I am still having some issues though. I have blender version 3.2 as suggested. I also tried this with blender version 3.1 as i was digging into the scripts and i saw something saying version 3.1.0 or something like that. I installed just the io_hkx animation subfolder. Checked import/export hkx in the addons list and it does bring up import Havok animation hkx. However, it does say "converter tool not found, check your addon preferences. I can see in the folder from the build, the blender-hkx.exe, both in the debug and release folder. I am curiouse if in need to go into the python script installed to blender and specify a location to the blender-hkx.exe?  
Thanks again and sorry to bother.

**Comment by McBearMan** [comment]
Hi all,

Sorry to cause any bother.

@StevedaveTodd how did you manage to get it to build? I am having trouble attempting this myself. I have all the requested files in a single directory matched to the reply from @jgernandt. However, I am still getting the error:

"Common/Base/hkBase.h' : No such file or directory."

How do I go about rectifying this?

Thank you.

**Comment by StevedaveTodd** [comment]
Should also add that the root folder you suggested, I named Data as I am used to working with Skyrim stuff. That Data folder has the blender-hkx folder and what was needed to build, the Havok SDK\hk2010_2_0_r1 and subfolders, and the pugixml stuff. I tried selecting the scripts in the io_hkx animation folder via blenders install addons, I selected the scripts and the checkbox for import hkx never came up so i drag and dropped the io-hkx animation folder into the blender's addon, scripts folder, which made the checkbox appear, and the import, export appear in the pie wheel in blender. Is there maybe a folder in blender that i need to drag and drop the built .exe into?

**Comment by StevedaveTodd** [comment]
Hello McBearMan, I am not sure if I did it 100% correctly, but it did build with no errors. I opened a drive on my compute and added a folder called Data, that is just what I chose as the root folder. I then created 3 new folders in there and named them blender-hkx, Havok SDK, and pugixml. In the blender-hkx folder, I drag and dropped these contents (blender-hkx folder, Debug folder, io-hkx animation folder, Release folder, gitignore file, blender-hkx.sin, LICENSE, and README.)
In the Havok SDK folder I drag and dropped the hk2010_2_0_r1 folder with all its subfolders and contents, And in the pugixml folder, I drag and dropped the folders docs, scripts, src, and tests.
I had to delete and unpack a new blender-hkx.sin into there as I had messed with it previosly and once I put a fresh .sin in there and opened it with visual studio 2019, and clicked build, it just went.   Surprised the crap out of me lol. I was pulling my hair out forever befor that.  Again, not sure I did it correctly, I hate visual studio cause I don't understand it, but good luck!

**Comment by StevedaveTodd** [comment]
Also, If you get it to build and get it working in blender, please let me know how you did it in blender. Love blender and I am super excited to delve into making hkx animations for Skyrim.

**Comment by StevedaveTodd** [comment]
Der Der Der....I feel like a dope lol. I just learned something about Blender. Never messed with the addon preferences in blender. The expand arrow lets you set the location of the converter tool and the location of the default skeleton etc.
THANK YOU jgernandt for the help with the build and especially for making an amazing blender addon!  Cant wait to delve into animations. THANKS!!!!!!!
